### ISSUE TITLE
Automatic rebuilds

### ISSUE THREAD

**Issue by MyIgel** [owntracks/recorderd#15]
The image rebuilds should be triggered after the debian jessie image changes to have the newest security updates installed

**Comment by jpmens** [comment]
Contributions, also in form of "how to accomplish that" welcome.

**Comment by jpmens** [comment]
Closing for lack of contribution

**Comment by MyIgel** [comment]
I fixed that for myself with [GitLab](https://code.caleano.com/caleano/container/owntracks-recorder) -> feel free to c&p

For github a similar way would be [Travis CI](https://travis-ci.org/) or directly with [docker hub](https://docs.docker.com/docker-hub/builds/#create-an-automated-build) (what i would prefer)
