### ISSUE TITLE
Setting Custom OTR_BROWSERAPIKEY

### ISSUE THREAD

**Issue by amwhalen** [owntracks/recorderd#4]
I have not been able to find a (correct) way to set the `OTR_BROWSERAPIKEY` variable for `ot-recorder` while using this Docker setup.

I have tried setting a Docker environment variable like `-e OTR_BROWSERAPIKEY='<key>'`, but that did not work. After a closer look at the docs, it seems like `OTR_BROWSERAPIKEY` cannot be passed in as an environment variable to ot-recorder, as I've already done with `OTR_USER` and `OTR_PASS`. 

Is there a preferred method to set this variable I just haven't found? Perhaps during the creation of this container there could be a way to store the `ot-recorder.default` file outside the container so it's editable, just like was done for `mosquitto.conf` and the other config and storage files.

Having this Dockerfile (especially the `.armhf` version for the raspberry pi) was hugely helpful in getting OwnTracks and the recorder setup. Thanks for the work on this!

**Comment by jpmens** [comment]
You are quite right: `$OTR_BROWSERAPIKEY` wasn't supported from the environment, but it is now: I've just comitted a fix for that which will surface into the next release (and thus Docker image).

The preferred method would be via the _defaults_ file, but I honestly don't know if you can edit that in the image ...

**Comment by amwhalen** [comment]
Perfect, thank you!
